// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzoxmBLjjOrh89gOvxQJJxVKXrIkCv4Rs',
    appId: '1:842196816948:web:f1ca96433115a7c13de661',
    messagingSenderId: '842196816948',
    projectId: 'the-fullbelly-project',
    authDomain: 'the-fullbelly-project.firebaseapp.com',
    storageBucket: 'the-fullbelly-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWyXT9XeFo5ux3EApiPxJuc8qbh82yvDM',
    appId: '1:842196816948:android:7885e003e1ee326b3de661',
    messagingSenderId: '842196816948',
    projectId: 'the-fullbelly-project',
    storageBucket: 'the-fullbelly-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMKFE6vnwwDsgZCRkf0pTnPqwG4PNfkBE',
    appId: '1:842196816948:ios:3108f484a0c98ace3de661',
    messagingSenderId: '842196816948',
    projectId: 'the-fullbelly-project',
    storageBucket: 'the-fullbelly-project.appspot.com',
    iosClientId: '842196816948-em47fgdia2guds7apog8ri0nv3ho3ajf.apps.googleusercontent.com',
    iosBundleId: 'com.example.thefullbellyprojectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMKFE6vnwwDsgZCRkf0pTnPqwG4PNfkBE',
    appId: '1:842196816948:ios:3108f484a0c98ace3de661',
    messagingSenderId: '842196816948',
    projectId: 'the-fullbelly-project',
    storageBucket: 'the-fullbelly-project.appspot.com',
    iosClientId: '842196816948-em47fgdia2guds7apog8ri0nv3ho3ajf.apps.googleusercontent.com',
    iosBundleId: 'com.example.thefullbellyprojectApp',
  );
}
